sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"

addons:
  apt:
    packages:
    # For SysDNS tests
    - unbound-host

install:
    - pip install -vr requirements.txt

# Some plugins use external APIs, and can cause tests to fail due to them being slow/down.
# --no-network disables these, and we can still allow tests that have network access to fail.
env:
    - SYSDNS_HOST_COMMAND="/usr/bin/unbound-host" TEST_ARGS="--no-network"
    - SYSDNS_HOST_COMMAND="/usr/bin/unbound-host" TEST_ARGS=""

script:
    - supybot-test -c --plugins-dir=. $TEST_ARGS --exclude=./Weather

notifications:
    email: false

matrix:
    allow_failures:
        - python: "3.2"
        - python: "3.3"
        - python: "pypy"
        - python: "pypy3"
        - python: "nightly"
        - env: SYSDNS_HOST_COMMAND="/usr/bin/unbound-host" TEST_ARGS=""

branches:
  except:
    - /^archive(-|\/).*$/
    - /^wip\/.*$/
